### ISSUE TITLE
beancount_import fails with example_data

### ISSUE THREAD

**Issue by ccdunder** [Evernight/lazy-beancount#3]
Error on startup:
```
Starting Fava on http://0.0.0.0:5000
INFO    : Initializing
INFO    : Loading journal
Listening at http://0.0.0.0:8101
INFO    : Matching source data
INFO    : preparing source beancount.ingest.importers.csv.Importer: "Assets:Monzo:Cash"
INFO    : prepare for beancount.ingest.importers.csv.Importer: "Assets:Monzo:Cash"
INFO    : preparing source beancount.ingest.importers.csv.Importer: "Assets:Revolut:Cash"
INFO    : prepare for beancount.ingest.importers.csv.Importer: "Assets:Revolut:Cash"
INFO    : preparing source beancount.ingest.importers.csv.Importer: "Assets:Revolut:Cash"
INFO    : prepare for beancount.ingest.importers.csv.Importer: "Assets:Revolut:Cash"
INFO    : preparing source beancount.ingest.importers.csv.Importer: "Assets:Revolut:Cash"
INFO    : prepare for beancount.ingest.importers.csv.Importer: "Assets:Revolut:Cash"
INFO    : preparing source beancount.ingest.importers.csv.Importer: "Assets:Wise:Cash"
INFO    : prepare for beancount.ingest.importers.csv.Importer: "Assets:Wise:Cash"
INFO    : preparing source beancount.ingest.importers.csv.Importer: "Assets:Wise:Cash"
INFO    : prepare for beancount.ingest.importers.csv.Importer: "Assets:Wise:Cash"
INFO    : preparing source beancount.ingest.importers.csv.Importer: "Assets:Wise:Cash"
INFO    : prepare for beancount.ingest.importers.csv.Importer: "Assets:Wise:Cash"
INFO    : preparing source uabean.importers.ibkr.Importer
INFO    : prepare for uabean.importers.ibkr.Importer
INFO    : preparing source uabean.importers.kraken.Importer
INFO    : prepare for uabean.importers.kraken.Importer
INFO    : preparing source uabean.importers.binance.Importer
INFO    : prepare for uabean.importers.binance.Importer
Traceback (most recent call last):
  File "/opt/venv/lib/python3.12/site-packages/beancount_import/webserver.py", line 514, in _handle_reconciler_loaded
    loaded_reconciler = loaded_future.result()
                        ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/opt/venv/lib/python3.12/site-packages/beancount_import/thread_helpers.py", line 13, in wrapper
    f.set_result(fn(*args, **kwargs))
                 ^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/beancount_import/reconcile.py", line 399, in __init__
    all_source_results = self._prepare_sources()
                         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/beancount_import/reconcile.py", line 524, in _prepare_sources
    source.prepare(self.editor, source_results)
  File "/opt/venv/lib/python3.12/site-packages/beancount_import/source/generic_importer_source_beangulp.py", line 67, in prepare
    logging.info(f'from {f.name} extracted {len(f_entries)} entries')
                         ^^^^^^
AttributeError: 'str' object has no attribute 'name'
(Pdb) f
'/workspace/beancount_import_data/binance/example-binance.csv'
```

**Comment by ccdunder** [comment]
Looks like beancount-imports [pulls in](https://github.com/Evernight/beancount-importers/blob/e0f92f9e9d804173dd40d6471266412b2911b897/setup.cfg#L54) a fork of beancount-import with a [patch](https://github.com/Evernight/beancount-import/commit/bc2bc097a79aba1171ebd5fa102cbef2e9050855) which added these logging lines.

**Comment by Evernight** [comment]
Thanks for the report and investigation! Yes, indeed it's in the fork with fixes some of which I plan to merge back into beancount-import later. These log lines are to simplify debugging as there's isn't much in the beancount-import itself even with the loglevel set to debug.
I fixed it in the beancount-import fork and will issue an update to lazy-beancount later today or tomorrow.

Note that binance importer (that failed in this case) is not guaranteed to work yet: I didn't check whether the actual output makes sense. I was mostly interested in the IBKR but can also help with porting other importers given there's interest and help with example files and testing.

**Comment by Evernight** [comment]
Fix merged, released new version
